#import private key
cleos wallet import --private-key 5Kby7vfsnkVWaXumUfT9r6gry3aq6bPNYrM64SVySV1kcHx9Jwh
cleos wallet import --private-key 5JuZRkieFU4tZvu8K9C5fv1ABjpnWJamSX1D1CGuBdS5uevWhaC
cleos wallet import --private-key 5Jhj9heVUT76QkMRTErAX3JcJhHyCfcdHusxWsjTwF9aKzkDPK2
cleos wallet import --private-key 5KQGGBFFzP7LfVQx4FSf1V3TBVrXohVTUguR27ebaXKrEbZwAX3
cleos wallet import --private-key 5JKGYUuZmaanx8gfxSVyApi611bCDRuV6wCuik17ZT7EiaBSH6G
cleos wallet import --private-key 5JdJu4MyqdBNKo93ccVyjh6AqhFkDTsJXg5S5bnk9nuNVs1FbZu
cleos wallet import --private-key 5Km24EUVHvC144ud9hDMPraFf3WMS9hJKEbajngBiEeSbGy27QX
cleos wallet import --private-key 5JtCbMePqibxxuTUvPLwH5tmzdpxzqtaKzNZKmArJrcjvQjLMxv
